import Head from "next/head";
import { api } from "~/utils/api";
import { useRouter } from "next/router";
import Layout from "~/components/Layout";
export default function Home() {
  const {data,isFetched}= api.profile.getGroups.useQuery()
  
  return (
    <>
      <Head>
        <title>Dimension Lite</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Layout>
        {/* <button onClick={()=>{
          router.push("/zero")
        }}>
        boop

        </button> */}


          <div className="h-full w-full">
          <iframe src="https://www.loom.com/embed/0d7d4466f2514a709152682afde8a2c0?sid=2154d8a7-5100-4122-9e68-82f363f33f65"  allowFullScreen className="w-full h-full"></iframe>
          </div>
      </Layout>
        
      
   
      

    </>
  );
}
