import Head from "next/head";
import { api } from "~/utils/api";
import { useRouter } from "next/router";
import Layout from "~/components/Layout";
export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });
  const router = useRouter()
  const {data,isFetched}= api.profile.getGroups.useQuery()
  
  return (
    <>
      <Head>
        <title>Dimension Lite</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Layout>
        {/* <button onClick={()=>{
          router.push("/zero")
        }}>
        boop

        </button> */}

          index
      </Layout>
        

{

  isFetched && data?.groups?.map((group)=>{
    return (<>
      <div>{data.groups?.length}</div>
      <div key={group.id}>
        {group.name}
      </div>
      </>
    )
  })
}

    </>
  );
}
