import Head from "next/head";
import { api } from "~/utils/api";
import { useRouter } from "next/router";
export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });
  const router = useRouter()
  return (
    <>
      <Head>
        <title>Dimension Lite</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex-grow">
        
     
        {/* <button onClick={()=>{
          router.push("/zero")
        }}>
        boop

        </button> */}


      </div>
      
      
    </>
  );
}
